/* DROP DATABASE IF EXISTS `userMgmt`; */
CREATE DATABASE IF NOT EXISTS `userMgmt`;
USE `userMgmt`;

/* users */
CREATE TABLE USER (
  ID 				VARCHAR(40) 	NOT NULL,
  UID 				VARCHAR(100) 	NOT NULL,
  PASSWORD			VARCHAR(100) 	NOT NULL,
  FIRST_NAME 		VARCHAR(100) 	NOT NULL,
  LAST_NAME 		VARCHAR(100),
  EMAIL	 			VARCHAR(100),
  PRIMARY KEY (UID),
  CONSTRAINT UNIQUE_EMAIL UNIQUE KEY (EMAIL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO USER (ID, UID, PASSWORD, FIRST_NAME, LAST_NAME, EMAIL) 
VALUES
	(UUID(), 'pistonAdmin', 'pistonAdmin', 'Piston', 'Admin', NULL),
	(UUID(), 'piston', 'piston', 'Piston', NULL, NULL),
	(UUID(), 'tomcat', 'tomcat', 'Tomcat', NULL, NULL);
	
/* groups */	
CREATE TABLE GROUPS (
  ID 		VARCHAR(40) 	NOT NULL,
  NAME 		VARCHAR(100) 	NOT NULL,
  PRIMARY KEY (NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO GROUPS (ID, NAME) 
VALUES
	(UUID(), 'pistonAdmins');

/* users and groups mappings */	
CREATE TABLE USER_GROUP (
  USER_UID 		VARCHAR(100) 	NOT NULL,
  GROUP_NAME 	VARCHAR(100)	NOT NULL,
  PRIMARY KEY (USER_UID, GROUP_NAME),
  CONSTRAINT FOREIGN_USER_UID FOREIGN KEY (USER_UID) REFERENCES USER (UID) ON DELETE CASCADE,
  CONSTRAINT FOREIGN_GROUP_NAME FOREIGN KEY (GROUP_NAME) REFERENCES GROUPS (NAME) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO USER_GROUP (USER_UID, GROUP_NAME) 
VALUES
	('pistonAdmin', 'pistonAdmins');

/* roles */
CREATE TABLE ROLE (
  ID 				VARCHAR(40) 	NOT NULL,
  NAME 				VARCHAR(100) 	NOT NULL,
  PRIMARY KEY (NAME)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO ROLE (ID, NAME) 
VALUES
	(UUID(), 'manager-gui'),
	(UUID(), 'manager-jmx');

/* user role mappings */
CREATE TABLE USER_ROLE (
  UID 			VARCHAR(100) 	NOT NULL,
  ROLE_NAME 	VARCHAR(100)	NOT NULL,
  PRIMARY KEY (UID, ROLE_NAME),
  CONSTRAINT FOREIGN_UID FOREIGN KEY (UID) REFERENCES USER (UID) ON DELETE CASCADE,
  CONSTRAINT FOREIGN_ROLE_NAME FOREIGN KEY (ROLE_NAME) REFERENCES ROLE (NAME) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO USER_ROLE (UID, ROLE_NAME) 
VALUES
	('tomcat', 'manager-gui'),
	('tomcat', 'manager-jmx');
